title: kjd
email: "kyle [at] kylejdavis.com"
description: >
  Personal website of Kyle J. Davis, open source and developer advocate. Mostly hobbies and non-work musings about technology.
url: "" 
github_username:  stockholmux
copyright: "(c) Kyle J. Davis."
footer_notes: "I have to say it: Opinions here are my own and do not reflect those of my employer. " 

mastodon_username: linux_mclinuxface
mastodon_instance: fosstodon.org

# Build settings
remote_theme: stockholmux/jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-remote-theme
lang: en-CA


exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
